# Generated by Django 5.1.15 on 2026-09-28 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("game_id", models.CharField(max_length=64, unique=True)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "opponent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("suspicion_score", models.FloatField(default=0.0)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("REVIEWED", "Reviewed"),
                            ("CLEARED", "Cleared"),
                            ("ACTIONED", "Actioned"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["-suspicion_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSanction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("WARNING", "Warning"),
                            ("LIMITED", "Limited matchmaking"),
                            ("BANNED", "Banned"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "related_game_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "applied_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheatSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signal_type", models.CharField(db_index=True, max_length=64)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("game_id", models.CharField(db_index=True, max_length=64)),
                (
                    "opponent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("value", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["game_id", "signal_type"],
                        name="anticheat_c_game_id_0d25c4_idx",
                    )
                ],
            },
        ),
    ]
