# Generated by Django 5.1.15 on 2026-09-28 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PuzzleStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_puzzle_date", models.DateField(blank=True, null=True)),
                ("total_solved", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPuzzleRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("rating", models.IntegerField(default=1200)),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("puzzles_solved", models.PositiveIntegerField(default=0)),
                ("puzzles_failed", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fen",
                    models.CharField(
                        help_text="Position before the puzzle move", max_length=100
                    ),
                ),
                (
                    "solution",
                    models.JSONField(
                        help_text="List of moves [{'from':'e4','to':'e5'}, ...]"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=1200, help_text="Puzzle difficulty rating"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                            ("EXPERT", "Expert"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "themes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of theme tags e.g. ['fork','pin']",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Origin/source game",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("times_played", models.PositiveIntegerField(default=0)),
                ("times_solved", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating"],
                "indexes": [
                    models.Index(
                        fields=["status", "rating"],
                        name="puzzles_puz_status_0ba6ac_idx",
                    ),
                    models.Index(
                        fields=["difficulty"], name="puzzles_puz_difficu_a751d2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyPuzzle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_entries",
                        to="puzzles.puzzle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PuzzleAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("solved", models.BooleanField(default=False)),
                ("attempts_count", models.PositiveIntegerField(default=1)),
                ("hints_used", models.PositiveIntegerField(default=0)),
                ("time_taken_seconds", models.PositiveIntegerField(default=0)),
                ("rating_before", models.IntegerField(blank=True, null=True)),
                ("rating_after", models.IntegerField(blank=True, null=True)),
                ("rating_change", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="puzzles.puzzle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "puzzle"],
                        name="puzzles_puz_user_id_43ac38_idx",
                    )
                ],
            },
        ),
    ]
