# Generated by Django 5.1.15 on 2026-09-28 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIGame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "side",
                    models.CharField(
                        choices=[("w", "White"), ("b", "Black")],
                        default="w",
                        max_length=1,
                    ),
                ),
                ("level", models.CharField(default="medium", max_length=16)),
                (
                    "fen",
                    models.TextField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
                    ),
                ),
                ("moves", models.JSONField(default=list)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PLAYER_WIN", "Player win"),
                            ("AI_WIN", "AI win"),
                            ("DRAW", "Draw"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "draw_reason",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
