# Generated by Django 5.1.15 on 2026-05-26 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SWISS", "Swiss"),
                            ("ROUND_ROBIN", "Round Robin"),
                            ("KNOCKOUT", "Knockout"),
                        ],
                        default="SWISS",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("time_control_initial", models.IntegerField(default=600)),
                ("time_control_increment", models.IntegerField(default=5)),
                ("rating_min", models.IntegerField(blank=True, null=True)),
                ("rating_max", models.IntegerField(blank=True, null=True)),
                ("max_players", models.IntegerField(default=64)),
                ("min_players", models.IntegerField(default=4)),
                ("total_rounds", models.IntegerField(default=7)),
                ("current_round", models.IntegerField(default=0)),
                ("creator_id", models.CharField(max_length=255)),
                ("allow_bye", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tournaments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="tournaments_status_2bfcdf_idx"
                    ),
                    models.Index(fields=["type"], name="tournaments_type_e8a5df_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TournamentPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("seed", models.IntegerField(default=0)),
                ("score", models.FloatField(default=0.0)),
                ("tiebreak1", models.FloatField(default=0.0)),
                ("tiebreak2", models.FloatField(default=0.0)),
                ("has_bye", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_players",
                "ordering": ["-score", "-tiebreak1", "-tiebreak2"],
                "unique_together": {("tournament", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="TournamentRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("round_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_rounds",
                "ordering": ["round_number"],
                "unique_together": {("tournament", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="TournamentMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("game_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("1-0", "White Win"),
                            ("0-1", "Black Win"),
                            ("1/2-1/2", "Draw"),
                            ("BYE", "Bye"),
                            ("*", "Not Played"),
                        ],
                        default="*",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("board_number", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "black_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="black_matches",
                        to="tournaments.tournamentplayer",
                    ),
                ),
                (
                    "white_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="white_matches",
                        to="tournaments.tournamentplayer",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournamentround",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_matches",
                "ordering": ["board_number"],
                "indexes": [
                    models.Index(
                        fields=["tournament", "status"],
                        name="tournament__tournam_9dcd31_idx",
                    )
                ],
            },
        ),
    ]
